# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Nov  5 16:28:10 2023
# ------------------------------------------------

package:
  name: tk
  version: 8.6.13
source:
  - folder: tcl8.6.13
    sha256: 43a1fae7412f61ff11de2cfd05d28cfc3a73762f354a417c62370a54e2caf066
    url: https://downloads.sourceforge.net/tcl/tcl8.6.13-src.tar.gz
  - folder: tk8.6.13
    sha256: 2e65fa069a23365440a3c56c556b8673b5e32a283800d8d9b257e3f584ce0675
    url: https://downloads.sourceforge.net/tcl/tk8.6.13-src.tar.gz
build:
  detect_binary_files_with_prefix: true
  number: '101'
  run_exports:
    - tk >=8.6.13,<8.7.0a0
  string: noxft_h4845f30_101
  track_features: null
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_2
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_2
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libsanitizer 12.3.0 h0f45ef3_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - libx11-common-cos6-x86_64 1.6.4 h9b0a68f_1105
    - libx11-cos6-x86_64 1.6.4 h9b0a68f_1105
    - libx11-devel-cos6-x86_64 1.6.4 h9b0a68f_1105
    - libxau-cos6-x86_64 1.0.6 h9b0a68f_1105
    - libxcb-cos6-x86_64 1.12 h9b0a68f_1105
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 he073ed8_16
    - xorg-x11-proto-devel-cos6-x86_64 7.7 h9b0a68f_1105
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libzlib 1.2.13 hd590300_5
    - zlib 1.2.13 hd590300_5
  run:
    - libgcc-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f "${PREFIX}/bin/tclsh"
    - test -f "${PREFIX}/bin/wish"
    - test -f "${PREFIX}/bin/tclsh8.6"
    - test -f "${PREFIX}/bin/wish8.6"
    - test -f "${PREFIX}/include/tcl.h"
    - test -f "${PREFIX}/include/tclDecls.h"
    - test -f "${PREFIX}/include/tclPlatDecls.h"
    - test -f "${PREFIX}/include/tclPlatDecls.h"
    - test -f "${PREFIX}/include/tclTomMathDecls.h"
    - test -f "${PREFIX}/include/tclTomMath.h"
    - test -f "${PREFIX}/include/tk.h"
    - test -f "${PREFIX}/include/tkDecls.h"
    - test -f "${PREFIX}/include/tkPlatDecls.h"
    - test -f "${PREFIX}/lib/libtcl8.6.so"
    - test -f "${PREFIX}/lib/libtclstub8.6.a"
    - test -f "${PREFIX}/lib/libtk8.6.so"
    - test -f "${PREFIX}/lib/libtkstub8.6.a"
    - tclsh hello.tcl
    - tclsh8.6 hello.tcl
    - wish hello.tcl
    - wish8.6 hello.tcl
  files:
    - hello.tcl
about:
  dev_url: https://github.com/tcltk/tk
  home: http://www.tcl.tk/
  license: TCL
  license_family: BSD
  license_file: tcl8.6.13/license.terms
  summary: A dynamic programming language with GUI support.  Bundles Tcl and Tk.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - matthiasdiener
    - msarahan
    - ocefpaf
    - pelson
    - xhochy
