# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Dec  2 09:02:41 2024
# ------------------------------------------------

package:
  name: wheel
  version: 0.45.1
source:
  sha256: 661e1abd9198507b1409a20c02106d9670b2576e916d58f520316666abca6729
  url: https://pypi.org/packages/source/w/wheel/wheel-0.45.1.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/wheel_1733130221056/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -c "import flit_core.buildapi; flit_core.buildapi.build_wheel('.')" && /home/conda/feedstock_root/build_artifacts/wheel_1733130221056/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m installer --no-compile-bytecode wheel-*.whl
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - flit-core 3.10.1 pyhd8ed1ab_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - python 3.9.20 h13acc7a_1_cpython
    - python-installer 0.7.0 pyhd8ed1ab_0
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.9
test:
  commands:
    - pip check
    - wheel --help
  imports:
    - wheel
    - wheel.cli
  requires:
    - pip
    - python 3.9.*
about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241202.2.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/wheel-feedstock
  sha: b62f30a943ffcdba1381c2f828e676dbc353474d
