# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Dec 31 16:07:32 2024
# ------------------------------------------------

package:
  name: tqdm
  version: 4.67.1
source:
  sha256: f8aef9c52c08c13a65f30ea34f4e5aac3fd1a34959879d7e59e63027286627f2
  url: https://pypi.org/packages/source/t/tqdm/tqdm-4.67.1.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/tqdm_1735661334605/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.2 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - packaging 24.2 pyhd8ed1ab_2
    - pip 24.3.1 pyh8b19718_2
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - setuptools-scm 8.1.0 pyhd8ed1ab_1
    - setuptools_scm 8.1.0 hd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - toml 0.10.2 pyhd8ed1ab_1
    - tomli 2.2.1 pyhd8ed1ab_1
    - typing-extensions 4.12.2 hd8ed1ab_1
    - typing_extensions 4.12.2 pyha770c72_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - colorama
    - python >=3.9
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v
    - pytest -k "not tests_perf and not tests_tk"
  imports:
    - tqdm
  requires:
    - pip
    - pytest
    - pytest-asyncio >=0.24
    - pytest-cov
    - pytest-timeout
    - python 3.9.*
  source_files:
    - pyproject.toml
    - tests
about:
  dev_url: https://tqdm.github.io/docs/tqdm
  doc_source_url: https://github.com/tqdm/tqdm/blob/master/README.rst
  doc_url: https://github.com/tqdm/tqdm#tqdm
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0 or MIT
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241231.1.1
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - synapticarbors
  remote_url: https://github.com/conda-forge/tqdm-feedstock
  sha: 007554e3f910e6b2863ea71b87a95840c90bc760
