# This file created by conda-build 3.28.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Dec  9 18:19:03 2023
# ------------------------------------------------

package:
  name: libev
  version: '4.33'
source:
  sha256: 507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
  url: http://dist.schmorp.de/libev/Attic/libev-4.33.tar.gz
build:
  number: '2'
  run_exports:
    - libev >=4.33,<4.34.0a0
  string: hd590300_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_3
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_103
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libsanitizer 12.3.0 h0f45ef3_3
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - libtool 2.4.7 h27087fc_0
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
  run:
    - libgcc-ng >=12
about:
  home: http://software.schmorp.de/pkg/libev.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A full-featured and high-performance event loop that is loosely modeled
    after libevent, but without its limitations and bugs.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231209.1.1
  recipe-maintainers:
    - carlodri
    - petercable
    - wolfv
  remote_url: https://github.com/conda-forge/libev-feedstock
  sha: a012320b04376463b1f00539ea714688da15c24b
