# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.6
source:
  patches:
    - 4019.patch
  sha256: 30f35f71c1203369dc979ecde0400ffea93c27391bfd2ac5a9715d2173d92ff7
  url: https://github.com/facebook/zstd/archive/v1.5.6.tar.gz
build:
  number: 0
  run_exports:
    - zstd >=1.5.6,<1.6.0a0
  string: ha6fb4c9_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha885e6a_0
    - binutils_linux-64 2.40 hdade7a5_3
    - cmake-no-system 3.29.2 h59595ed_0
    - gcc_impl_linux-64 12.3.0 h58ffeeb_6
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 h2a574ab_6
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h55db66e_0
    - libgcc-devel_linux-64 12.3.0 h0223996_106
    - libgcc-ng 13.2.0 h77fa898_6
    - libgomp 13.2.0 h77fa898_6
    - libsanitizer 12.3.0 hb8811af_6
    - libstdcxx-devel_linux-64 12.3.0 h0223996_106
    - libstdcxx-ng 13.2.0 hc0a3c3a_6
    - make 4.3 hd18ef5c_1
    - ninja 1.12.0 h00ab1b0_0
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h77fa898_6
    - libgomp 13.2.0 h77fa898_6
    - libstdcxx-ng 13.2.0 hc0a3c3a_6
    - libzlib 1.2.13 hd590300_5
    - zlib 1.2.13 hd590300_5
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libzstd.so
    - test ! -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/include/zstd.h
    - zstd -be -i5
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags libzstd
    - cd cf_test
    - cmake $CMAKE_ARGS .
  files:
    - cf_test/
  requires:
    - cmake
    - gcc_linux-64 12.*
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  feedstock-name: zstd
  final: true
  flow_run_id: azure_20240503.2.1
  recipe-maintainers:
    - JohanMabille
    - hmaarrfk
    - msarahan
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstd-feedstock
  sha: fe360b67052e184a180a3fb0dbf2dec8cd582be1
