# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.30
source:
  fn: libsolv-0.7.30.tar.gz
  patches:
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
  sha256: ce4aa2f0e3c5c9ab99dced6a1810af3f670f1b98892394edc68ccabe7b272133
  url: https://github.com/openSUSE/libsolv/archive/0.7.30.tar.gz
build:
  number: 0
  run_exports:
    - libsolv >=0.7.30,<0.8.0a0
  string: h3509ff9_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_9
    - bzip2 1.0.8 hd590300_5
    - c-ares 1.32.1 h4bc722e_0
    - ca-certificates 2024.7.4 hbcca054_0
    - cmake 3.30.0 hf8c4bd3_0
    - gcc_impl_linux-64 12.3.0 h58ffeeb_13
    - gcc_linux-64 12.3.0 h9528a6a_9
    - gxx_impl_linux-64 12.3.0 h2a574ab_13
    - gxx_linux-64 12.3.0 ha28b414_9
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libcurl 8.8.0 hca28451_1
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.2 h59595ed_0
    - libgcc-devel_linux-64 12.3.0 h6b66f73_113
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 12.3.0 hb8811af_13
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-devel_linux-64 12.3.0 h6b66f73_113
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libuv 1.48.0 hd590300_0
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - ninja 1.12.1 h297d8ca_0
    - openssl 3.3.1 h4ab18f5_1
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libzlib 1.3.1 h4ab18f5_1
    - zlib 1.3.1 h4ab18f5_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/libsolv${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libsolvext${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libsolv.so.1"
    - test -f "${PREFIX}/include/solv/repo.h"
    - dumpsolv -h
    - cmake -G Ninja -S test/ -B build/ -D LIB_NAME="libsolv${SHLIB_EXT}" ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - cmake
    - gcc_linux-64 12.*
    - gxx_linux-64 12.*
    - ninja
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240712.1.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - pavelzw
    - wolfv
  remote_url: https://github.com/conda-forge/libsolv-feedstock
  sha: b5ac07fa8c398c9797eb56da6d78c8aed68f1225
