# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jan 15 13:30:27 2025
# ------------------------------------------------

package:
  name: conda
  version: 24.11.3
source:
  fn: conda-24.11.3.tar.gz
  sha256: 5c4e352e737315b6dc86448abbb0c76834b21ef1663b02c797d4f55af8be981c
  url: https://github.com/conda/conda/releases/download/24.11.3/conda-24.11.3.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda_1736947900115/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv && /home/conda/feedstock_root/build_artifacts/conda_1736947900115/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m conda init --install
  string: py312h7900ff3_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - boltons 24.0.0 pyhd8ed1ab_1
    - brotli-python 1.1.0 py312h2ec8cdc_2
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - certifi 2024.12.14 pyhd8ed1ab_0
    - cffi 1.17.1 py312h06ac9bb_0
    - charset-normalizer 3.4.1 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_1
    - editables 0.5 pyhd8ed1ab_1
    - h2 4.1.0 pyhd8ed1ab_1
    - hatch-vcs 0.4.0 pyhd8ed1ab_1
    - hatchling 1.27.0 pypyhd8ed1ab_0
    - hpack 4.0.0 pyhd8ed1ab_1
    - hyperframe 6.0.1 pyhd8ed1ab_1
    - idna 3.10 pyhd8ed1ab_1
    - importlib-metadata 8.5.0 pyha770c72_1
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libexpat 2.6.4 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.2 hee588c1_0
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libstdcxx-ng 14.2.0 h4852527_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - menuinst 2.2.0 py312h7900ff3_0
    - ncurses 6.5 h2d0b736_2
    - openssl 3.4.0 h7b32b05_1
    - packaging 24.2 pyhd8ed1ab_2
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 24.3.1 pyh8b19718_2
    - platformdirs 4.3.6 pyhd8ed1ab_1
    - pluggy 1.5.0 pyhd8ed1ab_1
    - pycparser 2.22 pyh29332c3_1
    - pysocks 1.7.1 pyha55dd90_7
    - python 3.12.8 h9e4cc4f_1_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h8228510_1
    - requests 2.32.3 pyhd8ed1ab_1
    - ruamel.yaml 0.18.10 py312h66e93f0_0
    - ruamel.yaml.clib 0.2.8 py312h66e93f0_1
    - setuptools 75.8.0 pyhff2d567_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.2.1 pyhd8ed1ab_1
    - tqdm 4.67.1 pyhd8ed1ab_1
    - trove-classifiers 2025.1.10.15 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_1
    - typing_extensions 4.12.2 pyha770c72_1
    - tzdata 2024b hc8b5060_0
    - urllib3 2.3.0 pyhd8ed1ab_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.21.0 pyhd8ed1ab_1
    - zstandard 0.23.0 py312hef9b889_1
    - zstd 1.5.6 ha6fb4c9_0
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=23.11.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=24.3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  downstreams:
    - conda-smithy
  files:
    - commands_to_test.sh
    - test_runner.sh
  imports:
    - conda
    - conda_env
  requires:
    - mock
    - pexpect
    - responses
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250110.2.2
  recipe-maintainers:
    - beeankha
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
  remote_url: https://github.com/conda-forge/conda-feedstock
  sha: 2f6ae5e0afc9e2ed3e7bc99189ba3e7eb548e983
