# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Sep 26 14:09:22 2024
# ------------------------------------------------

package:
  name: conda-libmamba-solver
  version: 24.9.0
source:
  folder: src/
  sha256: 77a78524719290468665c091cf073f2b97440bfea25c373105a997654063fdbe
  url: https://github.com/conda/conda-libmamba-solver/archive/24.9.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda-libmamba-solver_1727359833193/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install src/ -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=24.9.0
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-vcs 0.4.0 pyhd8ed1ab_0
    - hatchling 1.25.0 pyhd8ed1ab_0
    - importlib-metadata 8.5.0 pyha770c72_0
    - ld_impl_linux-64 2.43 h712a8e2_1
    - libexpat 2.6.3 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.1.0 h77fa898_1
    - libgcc-ng 14.1.0 h69a702a_1
    - libgomp 14.1.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.1 hadc24fc_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - packaging 24.1 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.2 pyh8b19718_1
    - pluggy 1.5.0 pyhd8ed1ab_0
    - python 3.12.6 hc5c86c4_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.1.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.9.12 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024a h8827d51_1
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.20.2 pyhd8ed1ab_0
  run:
    - boltons >=23.0.0
    - conda >=23.7.4
    - libmambapy >=1.5.6,<2.0a0
    - python >=3.8
test:
  commands:
    - conda create -n test --dry-run scipy --solver=libmamba
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy
  imports:
    - conda_libmamba_solver
about:
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: The fast mamba solver, now in conda!
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240926.1.1
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  remote_url: https://github.com/conda-forge/conda-libmamba-solver-feedstock
  sha: 8271634f01b764d6099882f7e37ccfd0ec7d0fa7
