# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Dec 22 09:22:34 2024
# ------------------------------------------------

package:
  name: urllib3
  version: 2.3.0
source:
  sha256: f8c5449b3cf0861679ce7e0503c7b44b5ec981bec0d1d3795a07f1ba96f0204d
  url: https://pypi.org/packages/source/u/urllib3/urllib3-2.3.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/urllib3_1734859416348/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - editables 0.5 pyhd8ed1ab_1
    - hatch-vcs 0.4.0 pyhd8ed1ab_1
    - hatchling 1.27.0 pypyhd8ed1ab_0
    - importlib-metadata 8.5.0 pyha770c72_1
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.2 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - packaging 24.2 pyhd8ed1ab_2
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 24.3.1 pyh8b19718_2
    - pluggy 1.5.0 pyhd8ed1ab_1
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - setuptools-scm 8.1.0 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.2.1 pyhd8ed1ab_1
    - trove-classifiers 2024.10.21.16 pyhd8ed1ab_1
    - typing-extensions 4.12.2 hd8ed1ab_1
    - typing_extensions 4.12.2 pyha770c72_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.21.0 pyhd8ed1ab_1
  run:
    - brotli-python >=1.0.9
    - h2 >=4,<5
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.9
    - zstandard >=0.18.0
test:
  commands:
    - pip check
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.util
  requires:
    - pip
    - python 3.9.*
about:
  dev_url: https://github.com/shazow/urllib3
  doc_url: https://urllib3.readthedocs.io/
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241222.2.1
  recipe-maintainers:
    - illia-v
    - ocefpaf
    - pquentin
    - sethmlarson
    - shazow
  remote_url: https://github.com/conda-forge/urllib3-feedstock
  sha: 2568c049c4e92c3d04e1a5b28dc6b5ac0d8de29e
