# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Nov  9 10:08:21 2024
# ------------------------------------------------

package:
  name: menuinst
  version: 2.2.0
source:
  sha256: c225bacefa9ee216e678d929d375e34f10856d87c1aba70a57c3d7974fda0cb7
  url: https://github.com/conda/menuinst/archive/2.2.0.tar.gz
build:
  number: '0'
  script:
    - rm -f "/home/conda/feedstock_root/build_artifacts/menuinst_1731146972698/work/menuinst/data/osx_launcher_*"
    - rm -f "/home/conda/feedstock_root/build_artifacts/menuinst_1731146972698/work/menuinst/data/appkit_launcher_*"
    - /home/conda/feedstock_root/build_artifacts/menuinst_1731146972698/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.2.0
  string: py312h7900ff3_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libexpat 2.6.4 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - packaging 24.1 pyhd8ed1ab_0
    - pip 24.3.1 pyh8b19718_0
    - python 3.12.7 hc5c86c4_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.3.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - setuptools_scm 8.1.0 hd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.2 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands: null
  imports:
    - menuinst
    - menuinst.api
about:
  doc_url: https://conda.github.io/menuinst/
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241109.1.1
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  remote_url: https://github.com/conda-forge/menuinst-feedstock
  sha: 9c36347356d4b8a2a1c3c5854dba1f96a2438dd6
