CI: azure
c_compiler: '*'
cdt_name: cos7
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: '*'
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
extend_keys:
- extend_keys
- ignore_build_only_deps
- ignore_version
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '2.7'
python_abi_tag: cp312
python_impl: '*'
python_impl_version: '3.12'
python_implementation: cpython
python_version: '3.12'
r_base: '3.5'
target_platform: linux-64
vc: '*'
zip_keys:
- - python_abi_tag
  - python_version
  - python_impl_version
  - python_implementation
- - python
  - python_impl
