# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Nov 26 02:32:14 2024
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.6
source:
  patches:
    - patches/0001-GH-100-Replace-unittest.makeSuite-with-unittest.defaultTest.patch
  sha256: b0014986321e77a36d8fe24827698aae076500c817133a700608bd677b77a998
  url: https://github.com/conda/pycosat/archive/0.6.6.tar.gz
build:
  number: '2'
  script: /home/conda/feedstock_root/build_artifacts/pycosat_1732588402431/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps -vv
  string: py312h66e93f0_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_2
    - binutils_linux-64 2.43 h4852527_2
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_7
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libgcc 14.2.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgomp 14.2.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.2.0 hc0a3c3a_1
    - sysroot_linux-64 2.17 h4a8ded7_18
    - tzdata 2024b hc8b5060_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libexpat 2.6.4 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - pip 24.3.1 pyh8b19718_0
    - python 3.12.7 hc5c86c4_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands:
    - pip check
    - python test_package.py "0.6.6"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/pycosat
  home: https://github.com/conda/pycosat
  license: MIT
  license_file:
    - COPYRIGHT
    - LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241125.9.1
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - nehaljwani
    - pelson
  remote_url: https://github.com/conda-forge/pycosat-feedstock
  sha: 55ebbd30d4b1f3b2bee07fddce6830c065c3b4d5
