# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Oct 12 09:13:04 2024
# ------------------------------------------------

package:
  name: ruamel.yaml.clib
  version: 0.2.8
source:
  - sha256: beb2e0404003de9a4cab9753a8805a8fe9320ee6673136ed7f04255fe60bb512
    url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-0.2.8.tar.gz
  - fn: _ruamel_yaml.pyx
    patches:
      - fix-typecasts-s390x._ruamel_yaml.pyx.patch
    sha256: fb6b5653201f1ed89a951f6931fda377737156c4f30cadbd240f4d28f607665a
    url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/0.2.8/tree/_ruamel_yaml.pyx?format=raw
  - fn: _ruamel_yaml.pxd
    patches:
      - fix-typecasts-s390x._ruamel_yaml.pxd.patch
    sha256: ee35a75fd753a369bee439ec7e1826e77c7feaabf9c3ec9cf2f58110c7a95656
    url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/0.2.8/tree/_ruamel_yaml.pxd?format=raw
build:
  number: '1'
  script:
    - cythonize _ruamel_yaml.pyx
    - /home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1728724466132/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m pip install . -vv
  string: py312h66e93f0_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_1
    - binutils_linux-64 2.43 h4852527_1
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_4
    - kernel-headers_linux-64 3.10.0 he073ed8_17
    - ld_impl_linux-64 2.43 h712a8e2_1
    - libgcc 14.1.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgomp 14.1.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.1.0 hc0a3c3a_1
    - sysroot_linux-64 2.17 h4a8ded7_17
    - tzdata 2024b hc8b5060_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - cython 3.0.11 py312h8fd2918_3
    - ld_impl_linux-64 2.43 h712a8e2_1
    - libexpat 2.6.3 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.1.0 h77fa898_1
    - libgcc-ng 14.1.0 h69a702a_1
    - libgomp 14.1.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.1 hadc24fc_0
    - libstdcxx 14.1.0 hc0a3c3a_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - pip 24.2 pyh8b19718_1
    - python 3.12.7 hc5c86c4_0_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h8228510_1
    - setuptools 75.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands:
    - python -c "from importlib.util import find_spec; assert find_spec('_ruamel_yaml')"
  downstreams:
    - ruamel.yaml
about:
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241012.1.1
  recipe-maintainers:
    - mbargull
    - ocefpaf
  remote_url: https://github.com/conda-forge/ruamel.yaml.clib-feedstock
  sha: d24d97d82ae0b570ff1935b9f3335bea4565c3b4
