# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Oct 24 09:31:40 2024
# ------------------------------------------------

package:
  name: truststore
  version: 0.10.0
source:
  sha256: 5da347c665714fdfbd46f738c823fe9f0d8775e41ac5fb94f325749091187896
  url: https://pypi.io/packages/source/t/truststore/truststore-0.10.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/truststore_1729762363021/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_1
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libexpat 2.6.3 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libmpdec 4.0.0 h4bc722e_0
    - libsqlite 3.47.0 hadc24fc_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - pip 24.2 pyh145f28c_1
    - python 3.13.0 h9ebbce0_100_cp313
    - python_abi 3.13 5_cp313
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.10
test:
  commands:
    - pip check
  imports:
    - truststore
  requires:
    - pip
about:
  dev_url: https://github.com/sethmlarson/truststore
  doc_url: https://truststore.readthedocs.io/en/latest/
  home: https://github.com/sethmlarson/truststore
  license: MIT
  license_file: LICENSE
  summary: Verify certificates using native system trust stores
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241024.2.1
  recipe-maintainers:
    - wolfv
  remote_url: https://github.com/conda-forge/truststore-feedstock
  sha: d7b9fdedc8a4c0b80fd6dadc6ae966491af78b25
