# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Dec  3 13:29:03 2024
# ------------------------------------------------

package:
  name: platformdirs
  version: 4.3.6
source:
  sha256: 357fb2acbc885b0419afd3ce3ed34564c13c9b95c89360cd9563f73aa5e2b907
  url: https://pypi.org/packages/source/p/platformdirs/platformdirs-4.3.6.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/platformdirs_1733232627818/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - editables 0.5 pyhd8ed1ab_1
    - hatch-vcs 0.4.0 pyhd8ed1ab_1
    - hatchling 1.26.3 pypyhff2d567_0
    - importlib-metadata 8.5.0 pyha770c72_1
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - packaging 24.2 pyhd8ed1ab_2
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.3.1 pyh8b19718_0
    - pluggy 1.5.0 pyhd8ed1ab_1
    - python 3.9.20 h13acc7a_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - setuptools-scm 8.1.0 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.2.1 pyhd8ed1ab_0
    - trove-classifiers 2024.10.21.16 pyhd8ed1ab_1
    - typing-extensions 4.12.2 hd8ed1ab_1
    - typing_extensions 4.12.2 pyha770c72_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.21.0 pyhd8ed1ab_1
  run:
    - python >=3.9
test:
  commands:
    - pip check
    - mypy -p platformdirs --ignore-missing-imports
  imports:
    - platformdirs
  requires:
    - mypy
    - pip
    - python 3.9.*
about:
  home: https://github.com/tox-dev/platformdirs
  license: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241203.2.1
  recipe-maintainers:
    - adament
    - bollwyvl
    - gaborbernat
  remote_url: https://github.com/conda-forge/platformdirs-feedstock
  sha: c6f468a0e6db68718683d68a03c51c95d9266549
