# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct 13 17:40:55 2024
# ------------------------------------------------

package:
  name: frozendict
  version: 2.4.6
source:
  fn: frozendict-2.4.6.tar.gz
  sha256: df7cd16470fbd26fc4969a208efadc46319334eb97def1ddf48919b351192b8e
  url: https://pypi.io/packages/source/f/frozendict/frozendict-2.4.6.tar.gz
build:
  number: '0'
  script: python -m pip install . --no-deps -vv
  string: py312h66e93f0_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_1
    - binutils_linux-64 2.43 h4852527_1
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_4
    - kernel-headers_linux-64 3.10.0 he073ed8_17
    - ld_impl_linux-64 2.43 h712a8e2_1
    - libgcc 14.1.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgomp 14.1.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.1.0 hc0a3c3a_1
    - sysroot_linux-64 2.17 h4a8ded7_17
    - tzdata 2024b hc8b5060_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_1
    - libexpat 2.6.3 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.1.0 h77fa898_1
    - libgcc-ng 14.1.0 h69a702a_1
    - libgomp 14.1.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.1 hadc24fc_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - pip 24.2 pyh8b19718_1
    - python 3.12.7 hc5c86c4_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  imports:
    - frozendict
about:
  dev_url: https://github.com/Marco-Sulla/python-frozendict
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241013.2.1
  recipe-maintainers:
    - Marco-Sulla
    - ltalirz
  remote_url: https://github.com/conda-forge/frozendict-feedstock
  sha: 1ed7e1c6ccf60b2cf38cabaac62f06be804da503
