# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: yaml-cpp
  version: 0.8.0
source:
  sha256: fbe74bbdcee21d656715688706da3c8becfd946d92cd44705cc6098bb23b3a16
  url: https://github.com/jbeder/yaml-cpp/archive/refs/tags/0.8.0.tar.gz
build:
  number: 0
  run_exports:
    - yaml-cpp >=0.8.0,<0.9.0a0
  string: h59595ed_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.19.1 hd590300_0
    - ca-certificates 2023.7.22 hbcca054_0
    - cmake 3.27.6 hcfe8598_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_2
    - gcc_linux-64 12.3.0 h76fc315_2
    - gxx_impl_linux-64 12.3.0 he2b93b0_2
    - gxx_linux-64 12.3.0 h8a814eb_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libcurl 8.3.0 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libexpat 2.5.0 hcb278e6_1
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_2
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libnghttp2 1.52.0 h61bc06f_0
    - libsanitizer 12.3.0 h0f45ef3_2
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - libuv 1.46.0 hd590300_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - ninja 1.11.1 h924138e_0
    - openssl 3.1.3 hd590300_0
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.12 he073ed8_16
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.5 hfc55251_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
test:
  commands:
    - test -f "${PREFIX}/lib/libyaml-cpp${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libyaml-cpp.a"
    - test -f "${PREFIX}/lib/cmake/yaml-cpp/yaml-cpp-config.cmake"
    - cmake -G Ninja -S test/ -B build-test/ ${CMAKE_ARGS}
    - cmake --build build-test/
    - cmake --build build-test/ --target test
  files:
    - test/
  requires:
    - cmake
    - gcc_linux-64 12.*
    - gxx_linux-64 12.*
    - ninja
about:
  dev_url: https://github.com/jbeder/yaml-cpp
  doc_url: https://github.com/jbeder/yaml-cpp/wiki/Tutorial
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AntoinePrv
    - allanleal
    - marcelotrevisani
    - seanyen
    - tadeu
    - wolfv
