# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Sep  5 18:21:07 2024
# ------------------------------------------------

package:
  name: cffi
  version: 1.17.1
source:
  patches:
    - 0001-Link-to-dl-library.patch
    - 0002-setup-linux.patch
  sha256: 1c39c6016c32bc48dd54561950ebd6836e1670f2ae46128f67cf49e789c52824
  url: https://pypi.io/packages/source/c/cffi/cffi-1.17.1.tar.gz
build:
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/cffi_1725560558132/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py312h06ac9bb_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_1
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_1
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc 14.1.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgcc-ng 14.1.0 h69a702a_1
    - libgomp 14.1.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.1.0 hc0a3c3a_1
    - patch 2.7.6 h7f98852_1002
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h8827d51_1
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.1.0 h77fa898_1
    - libgcc-ng 14.1.0 h69a702a_1
    - libgomp 14.1.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.1 hadc24fc_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - pip 24.2 pyh8b19718_1
    - pycparser 2.22 pyhd8ed1ab_0
    - python 3.12.5 h2ad013b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 73.0.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h8827d51_1
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libffi >=3.4,<4.0a0
    - libgcc >=13
    - pycparser
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands:
    - pip check
    - python -X faulthandler -c "from cffi import FFI; print(FFI().dlopen(None))"
  imports:
    - _cffi_backend
    - cffi
  requires:
    - openssl *
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://bitbucket.org/cffi/cffi/overview
  doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
  doc_url: http://cffi.readthedocs.org
  home: https://bitbucket.org/cffi/cffi
  license: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240905.2.1
  recipe-maintainers:
    - goanpeca
    - katietz
    - mingwandroid
    - ocefpaf
  remote_url: https://github.com/conda-forge/cffi-feedstock
  sha: 9691447b974019208e78fde1979ace33568169af
