# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libssh2
  version: 1.11.1
source:
  sha256: d9ec76cbe34db98eec3539fe2c899d26b0c837cb3eb466a56b0f109cabf658f7
  url: https://www.libssh2.org/download/libssh2-1.11.1.tar.gz
build:
  number: 0
  run_exports:
    - libssh2 >=1.11.1,<2.0a0
  string: hf672d98_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_2
    - binutils_linux-64 2.43 h4852527_2
    - cmake-no-system 3.31.1 h5888daf_0
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_7
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libgcc 14.2.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgomp 14.2.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.2.0 hc0a3c3a_1
    - make 4.4.1 hb9d3cd8_2
    - sysroot_linux-64 2.17 h4a8ded7_18
    - tzdata 2024b hc8b5060_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - ca-certificates 2024.8.30 hbcca054_0
    - libgcc 14.2.0 h77fa898_1
    - libgomp 14.2.0 h77fa898_1
    - libzlib 1.3.1 hb9d3cd8_2
    - openssl 3.4.0 hb9d3cd8_0
    - zlib 1.3.1 hb9d3cd8_2
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.4.0,<4.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test ! -f $PREFIX/lib/libssh2.a
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  feedstock-name: libssh2
  final: true
  flow_run_id: azure_20241123.2.1
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
    - shadowwalkersb
    - xhochy
  remote_url: https://github.com/conda-forge/libssh2-feedstock
  sha: 66da9630a14e802670c8434ad6ffba388386603d
