# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Dec 16 20:20:17 2024
# ------------------------------------------------

package:
  name: certifi
  version: 2024.12.14
source:
  - folder: certifi
    sha256: b650d30f370c2b724812bee08008be0c4163b163ddaec3f2546c1caf65f191db
    url: https://pypi.org/packages/source/c/certifi/certifi-2024.12.14.tar.gz
  - folder: boostrap_wheels
    sha256: 3790624780082365f47549d032f3770eeb2b1e8bd1f7b2e02dace1afa361b4ed
    url: https://pypi.org/packages/py3/p/pip/pip-24.3.1-py3-none-any.whl
  - folder: boostrap_wheels
    sha256: ce74b49e8f7110f9bf04883b730f4765b774ef3ef28f722cce7c273d253aaf7d
    url: https://pypi.org/packages/py3/s/setuptools/setuptools-75.6.0-py3-none-any.whl
  - folder: boostrap_wheels
    sha256: 708e7481cc80179af0e556bbf0cc00b8444c7321e2700b8d8580231d13017248
    url: https://pypi.org/packages/py3/w/wheel/wheel-0.45.1-py3-none-any.whl
build:
  noarch: python
  number: '0'
  script:
    - cd certifi
    - /home/conda/feedstock_root/build_artifacts/certifi_1734380492396/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
      -m pip install . -vv
  script_env:
    - 'PYTHONPATH=/home/conda/feedstock_root/build_artifacts/certifi_1734380492396/work/boostrap_wheels:'
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.2 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
  run:
    - python >=3.9
test:
  imports:
    - certifi
  requires:
    - python 3.9.*
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/certifi
  home: http://certifi.io/
  license: ISC
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241216.10.1
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: https://github.com/conda-forge/certifi-feedstock
  sha: 3453f5ffce60495501c14c617bc0be65a0c712bd
