# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: reproc-cpp
  version: 14.2.5.post0
source:
  - patches:
      - 103-remove-fd-limit.patch
    sha256: 69467be0cfc80734b821c54ada263c8f1439f964314063f76b7cf256c3dc7ee8
    url: https://github.com/DaanDeMeyer/reproc/archive/v14.2.5.tar.gz
build:
  number: 0
  run_exports:
    - reproc-cpp >=14.2,<15.0a0
  string: h5888daf_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_2
    - binutils_linux-64 2.43 h4852527_2
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.32.3 h4bc722e_0
    - ca-certificates 2024.8.30 hbcca054_0
    - cmake 3.30.5 hf9cb763_0
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_6
    - gxx_impl_linux-64 13.3.0 hdbfa832_1
    - gxx_linux-64 13.3.0 h6834431_6
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libcurl 8.10.1 hbbe4b11_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.4 h5888daf_0
    - libgcc 14.2.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnghttp2 1.64.0 h161d5f1_0
    - libsanitizer 13.3.0 heb74ff8_1
    - libssh2 1.11.0 h0841786_0
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libstdcxx-devel_linux-64 13.3.0 h84ea5a7_101
    - libstdcxx-ng 14.2.0 h4852527_1
    - libuv 1.49.2 hb9d3cd8_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - ninja 1.12.1 h297d8ca_0
    - openssl 3.4.0 hb9d3cd8_0
    - rhash 1.4.5 hb9d3cd8_0
    - sysroot_linux-64 2.17 h4a8ded7_18
    - tzdata 2024b hc8b5060_0
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 14.2.0 h77fa898_1
    - libgomp 14.2.0 h77fa898_1
    - libstdcxx 14.2.0 hc0a3c3a_1
    - reproc 14.2.5.post0 hb9d3cd8_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - libstdcxx >=13
    - reproc 14.2.5.post0 hb9d3cd8_0
test:
  commands:
    - test -f ${PREFIX}/include/reproc++/run.hpp
    - test -f ${PREFIX}/lib/libreproc++${SHLIB_EXT}
    - test -f ${PREFIX}/lib/cmake/reproc++/reproc++-config.cmake
    - test ! -f ${PREFIX}/lib/libreproc.a
    - test ! -f ${PREFIX}/lib/libreproc++.a
    - cmake -G Ninja -S test-cpp/ -B build-test-cpp/ ${CMAKE_ARGS}
    - cmake --build build-test-cpp/
    - cmake --build build-test-cpp/ --target test
  files:
    - test-cpp/
  requires:
    - cmake
    - gcc_linux-64 13.*
    - gxx_linux-64 13.*
    - ninja
about:
  dev_url: https://github.com/DaanDeMeyer/reproc
  home: https://github.com/DaanDeMeyer/reproc
  license: MIT
  license_file: LICENSE
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies
    starting, stopping and communicating with external programs.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241118.2.1
  recipe-maintainers:
    - AntoinePrv
    - DaanDeMeyer
    - wolfv
  remote_url: https://github.com/conda-forge/reproc-feedstock
  sha: 0d8c38aefb9f2dc6ba1129b03d070f7f082dafff
