# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libgomp
  version: 14.2.0
source:
  - patches:
      - patches/0002-allow-commands-in-main-specfile.patch
      - patches/0003-patch-zoneinfo_dir_override-to-point-to-our-tzdata.patch
      - patches/0004-add-ldl-to-libstdc___la_LDFLAGS.patch
      - patches/0005-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
      - patches/0006-fix-tzdb-for-newer-format.patch
    sha256: 7d376d445f93126dc545e2c0086d0f647c3094aae081cdb78f42ce2bc25e7293
    url: https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.gz
build:
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'
  number: 1
  run_exports:
    strong:
      - _openmp_mutex >=4.5
  string: h77fa898_1
requirements:
  host:
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - sysroot_linux-64 2.12 he073ed8_16
  run:
    - _libgcc_mutex 0.1 conda_forge
test:
  commands:
    - test -f ${PREFIX}/lib/libgomp.so.1.0.0
    - test ! -f ${PREFIX}/lib/libgomp.so.1
  requires:
    - sysroot_linux-64
about:
  home: https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GCC OpenMP implementation.
extra:
  copy_test_source_files: true
  feedstock-name: ctng-compilers-feedstock
  final: true
  flow_run_id: azure_20241015.1.1
  recipe-maintainers:
    - beckermr
    - isuruf
    - timsnyder
    - xhochy
  remote_url: https://github.com/conda-forge/ctng-compilers-feedstock
  sha: 55c5af125402e8a59e38fdeb72d47dafdc7e67f5
