# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct 15 14:52:25 2024
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.11.0
source:
  sha256: 407ec0bd3f65fccc3ac8e02f7ba3bb31c95ceca10ebdcfe66120bf56db28e59b
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.11.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda-package-streaming_1729004031731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install --no-build-isolation . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_1
    - ld_impl_linux-64 2.43 h712a8e2_1
    - libexpat 2.6.3 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.1.0 h77fa898_1
    - libgcc-ng 14.1.0 h69a702a_1
    - libgomp 14.1.0 h77fa898_1
    - libmpdec 4.0.0 h4bc722e_0
    - libsqlite 3.46.1 hadc24fc_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - pip 24.2 pyh145f28c_1
    - python 3.13.0 h9ebbce0_100_cp313
    - python_abi 3.13 5_cp313
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming.url
  requires:
    - pip
    - requests
about:
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Download metadata from conda packages without transferring entire file.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241015.1.1
  recipe-maintainers:
    - dholth
  remote_url: https://github.com/conda-forge/conda-package-streaming-feedstock
  sha: 3cfbed3a15e942a0e0ed0988ccbaf323b0d0531f
