@echo off
set "ADDR2LINE=%CONDA_BACKUP_ADDR2LINE%"
set "CONDA_BACKUP_ADDR2LINE="

set "AR=%CONDA_BACKUP_AR%"
set "CONDA_BACKUP_AR="

set "AS=%CONDA_BACKUP_AS%"
set "CONDA_BACKUP_AS="

set "CXXFILT=%CONDA_BACKUP_CXXFILT%"
set "CONDA_BACKUP_CXXFILT="

set "ELFEDIT=%CONDA_BACKUP_ELFEDIT%"
set "CONDA_BACKUP_ELFEDIT="

set "GPROF=%CONDA_BACKUP_GPROF%"
set "CONDA_BACKUP_GPROF="

set "LD=%CONDA_BACKUP_LD%"
set "CONDA_BACKUP_LD="

set "NM=%CONDA_BACKUP_NM%"
set "CONDA_BACKUP_NM="

set "OBJCOPY=%CONDA_BACKUP_OBJCOPY%"
set "CONDA_BACKUP_OBJCOPY="

set "OBJDUMP=%CONDA_BACKUP_OBJDUMP%"
set "CONDA_BACKUP_OBJDUMP="

set "RANLIB=%CONDA_BACKUP_RANLIB%"
set "CONDA_BACKUP_RANLIB="

set "READELF=%CONDA_BACKUP_READELF%"
set "CONDA_BACKUP_READELF="

set "SIZE=%CONDA_BACKUP_SIZE%"
set "CONDA_BACKUP_SIZE="

set "STRINGS=%CONDA_BACKUP_STRINGS%"
set "CONDA_BACKUP_STRINGS="

set "STRIP=%CONDA_BACKUP_STRIP%"
set "CONDA_BACKUP_STRIP="

set "DLLTOOL=%CONDA_BACKUP_DLLTOOL%"
set "CONDA_BACKUP_DLLTOOL="

set "DLLWRAP=%CONDA_BACKUP_DLLWRAP%"
set "CONDA_BACKUP_DLLWRAP="

set "WINDMC=%CONDA_BACKUP_WINDMC%"
set "CONDA_BACKUP_WINDMC="

set "WINDRES=%CONDA_BACKUP_WINDRES%"
set "CONDA_BACKUP_WINDRES="
