CI: azure
c_compiler: gcc
c_stdlib: sysroot
c_stdlib_version: '2.17'
cdt_name: cos7
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_target_platform: linux-64
ctng_vendor: conda_cos6
cxx_compiler: gcc_bootstrap
cxx_compiler_version: '13'
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
extend_keys:
- ignore_build_only_deps
- extend_keys
- ignore_version
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.12'
r_base: '3.5'
target_platform: linux-64
triplet: x86_64-conda-linux-gnu
zip_keys:
- - triplet
  - ctng_vendor
  - cross_target_platform
- - c_stdlib_version
  - cdt_name
