# This file created by conda-build 25.1.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jan 17 13:00:46 2025
# ------------------------------------------------

package:
  name: tzdata
  version: 2025a
source:
  - sha256: 4d5fcbc72c7c450ebfe0b659bd0f1c02fbf52fd7f517a9ea13fe71c21eb5f0d0
    url: https://data.iana.org/time-zones/releases/tzdata2025a.tar.gz
  - sha256: 119679d59f76481eb5e03d3d2a47d7870d592f3999549af189dbd31f2ebf5061
    url: https://data.iana.org/time-zones/releases/tzcode2025a.tar.gz
build:
  ignore_run_exports_from:
    - clang_osx-64 18.*
    - macosx_deployment_target_osx-64 10.13.*
  noarch: generic
  number: '0'
  string: h78e105d_0
requirements:
  build:
    - ca-certificates 2024.12.14 h8857fd0_0
    - cctools_osx-64 1010.6 h00edd4c_2
    - clang 18.1.8 default_h179603d_5
    - clang-18 18.1.8 default_h0c94c6a_5
    - clang_impl_osx-64 18.1.8 h6a44ed1_23
    - clang_osx-64 18.1.8 h7e5c614_23
    - clangxx 18.1.8 default_h179603d_5
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - ld64_osx-64 951.9 hc8d1a19_2
    - libclang-cpp18.1 18.1.8 default_h0c94c6a_5
    - libcxx 19.1.7 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_7
    - libiconv 1.17 hd75f5a5_2
    - libllvm18 18.1.8 h9ce406d_2
    - liblzma 5.6.3 hd471939_1
    - libxml2 2.13.5 he8ee3e7_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 h9ce406d_2
    - llvm-tools-18 18.1.8 h9ce406d_2
    - macosx_deployment_target_osx-64 10.13 hbc8f3bb_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_2
    - openssl 3.4.0 hc426f3f_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.6 h915ae27_0
  host: []
  run: []
test:
  commands:
    - test -f "${PREFIX}/share/zoneinfo/leapseconds"
    - test -f "${PREFIX}/share/zoneinfo/leap-seconds.list"
    - test -f "${PREFIX}/share/zoneinfo/iso3166.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone1970.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone.tab"
    - test -f "${PREFIX}/share/zoneinfo/tzdata.zi"
    - "dirs=\"$(\n  find \"${PREFIX}\" -mindepth 1 -maxdepth 2 \\\n  \\! -path \"\
      ${PREFIX}/share\" \\! -path \"${PREFIX}/conda-meta*\"\n)\"\ntest \"${dirs}\"\
      \ = \"${PREFIX}/share/zoneinfo\"\n"
    - "heads=\"$(\n  find \"${PREFIX}/share/zoneinfo\" -type f \\\n    \\! -name \\\
      *.zi \\! -name \\*.tab \\! -name leapseconds \\! -name leap-seconds.list \\\n\
      \    -exec sh -c 'head -c4 $1 && echo' sh {} \\; \\\n    | uniq\n)\"\ntest \"\
      ${heads}\" = TZif\n"
about:
  description: 'The Time Zone Database (called tz, tzdb or zoneinfo) contains code

    (the tzcode package) and data (this package) that represent the

    history of local time for many representative

    locations around the globe.  It is updated periodically to reflect

    changes made by political bodies to time zone boundaries, UTC offsets,

    and daylight-saving rules.

    '
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  home: https://www.iana.org/time-zones
  license: LicenseRef-Public-Domain
  license_file: LICENSE
  summary: The Time Zone Database (called tz, tzdb or zoneinfo) data
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250117.2.1
  recipe-maintainers:
    - h-vetinari
    - mbargull
    - ocefpaf
    - pganssle
  remote_url: https://github.com/conda-forge/tzdata-feedstock
  sha: 91777b7ce4823be56db448077ec79647617c32d2
