# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Mar 23 00:40:06 2023
# ------------------------------------------------

package:
  name: readline
  version: '8.2'
source:
  sha256: 3feb7171f16a84ee82ca18a36d7b9be109a52c04f492a053331d7d1095007c35
  url: https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
build:
  number: '1'
  run_exports:
    - readline >=8.2,<9.0a0
  string: h8228510_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_linux-64 2.39 h5fc0e48_11
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_linux-64 11.3.0 he6f903b_11
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libsanitizer 11.3.0 h239ccf8_19
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libtool 2.4.7 h27087fc_0
    - make 4.3 hd18ef5c_1
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_15
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - ncurses 6.3 h27087fc_1
  run:
    - libgcc-ng >=12
    - ncurses >=6.3,<7.0a0
test:
  commands:
    - test ! -f ${PREFIX}/lib/libreadline.a
    - test -f ${PREFIX}/lib/libreadline${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libhistory.a
    - test -f ${PREFIX}/lib/libhistory${SHLIB_EXT}
about:
  home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL-3.0-only
  license_file: COPYING
  summary: library for editing command lines as they are typed in
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - asmeurer
    - croth1
    - jakirkham
    - mingwandroid
    - msarahan
    - msarahan
    - ocefpaf
    - pelson
