CI: azure
c_compiler: gcc
c_stdlib: sysroot
c_stdlib_version: '2.17'
cdt_name: conda
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '13'
docker_image: quay.io/condaforge/linux-anvil-x86_64:alma9
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fmt: '11'
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
libarchive: '3.7'
lua: '5'
numpy: '1.26'
openssl: '3'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
pybind11_abi: '4'
python: 3.12.* *_cpython
r_base: '3.5'
spdlog: '1.15'
target_platform: linux-64
zstd: '1.5'
