# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Sep  2 19:30:59 2024
# ------------------------------------------------

package:
  name: zstandard
  version: 0.23.0
source:
  sha256: b2d8c62d08e7255f68f7a740bae85b3c9b8e5466baa9cbf7f57f1cde0ac6bc09
  url: https://pypi.io/packages/source/z/zstandard/zstandard-0.23.0.tar.gz
build:
  number: '1'
  string: py312hef9b889_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_1
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_1
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc 14.1.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgomp 14.1.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.1.0 hc0a3c3a_1
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h8827d51_1
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - cffi 1.17.0 py312h06ac9bb_1
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.1.0 h77fa898_1
    - libgcc-ng 14.1.0 h69a702a_1
    - libgomp 14.1.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx 14.1.0 hc0a3c3a_1
    - libstdcxx-ng 14.1.0 h4852527_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 he02047a_1
    - openssl 3.3.1 hb9d3cd8_3
    - pip 24.2 pyh8b19718_1
    - pycparser 2.22 pyhd8ed1ab_0
    - python 3.12.5 h2ad013b_0_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h8228510_1
    - setuptools 72.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h8827d51_1
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  run:
    - __glibc >=2.17,<3.0.a0
    - cffi >=1.11
    - libgcc >=13
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
    - zstd >=1.5.6,<1.5.7.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240902.3.1
  recipe-maintainers:
    - pavelzw
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstandard-feedstock
  sha: 2894dec506a78515d0a7a4fc8914910be70deb10
