# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Dec 20 21:22:42 2024
# ------------------------------------------------

package:
  name: distro
  version: 1.9.0
source:
  fn: distro-1.9.0.tar.gz
  sha256: 2fa77c6fd8940f116ee1d6b94a2f90b13b5ea8d019b98bc8bafdcabcdd9bdbed
  url: https://pypi.org/packages/source/d/distro/distro-1.9.0.tar.gz
build:
  entry_points:
    - distro = distro.distro:main
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/distro_1734729835256/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.2 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - pip 24.3.1 pyh8b19718_2
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.9
test:
  commands:
    - pip check
    - distro --help
    - pytest -vvv --capture=tee-sys tests
  imports:
    - distro
  requires:
    - pip
    - pytest
    - python 3.9.*
  source_files:
    - tests
about:
  dev_url: https://github.com/nir0s/distro
  doc_url: http://distro.readthedocs.io/en/latest/
  home: https://github.com/nir0s/distro
  license: Apache-2.0
  license_file: LICENSE
  summary: Provides information about the OS distribution it runs on, such as a reliable
    machine-readable ID, or version information.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241220.2.1
  recipe-maintainers:
    - abloemert
    - thewchan
  remote_url: https://github.com/conda-forge/distro-feedstock
  sha: c644127e426e8ca5bed76ec65c814d969b630f63
