# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.64.0
source:
  sha256: 20e73f3cf9db3f05988996ac8b3a99ed529f4565ca91a49eb0550498e10621e8
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.64.0/nghttp2-1.64.0.tar.gz
build:
  number: 0
  run_exports:
    - libnghttp2 >=1.64.0,<2.0a0
  string: h161d5f1_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_1
    - binutils_linux-64 2.43 h4852527_1
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_5
    - gxx_impl_linux-64 13.3.0 hdbfa832_1
    - gxx_linux-64 13.3.0 h6834431_5
    - kernel-headers_linux-64 3.10.0 he073ed8_17
    - ld_impl_linux-64 2.43 h712a8e2_1
    - libgcc 14.2.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libstdcxx-devel_linux-64 13.3.0 h84ea5a7_101
    - make 4.4.1 hb9d3cd8_2
    - pkg-config 0.29.2 h4bc722e_1009
    - sysroot_linux-64 2.17 h4a8ded7_17
    - tzdata 2024b hc8b5060_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - c-ares 1.32.3 h4bc722e_0
    - ca-certificates 2024.8.30 hbcca054_0
    - libev 4.33 hd590300_2
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libzlib 1.3.1 hb9d3cd8_2
    - openssl 3.3.2 hb9d3cd8_0
    - zlib 1.3.1 hb9d3cd8_2
  run:
    - __glibc >=2.17,<3.0.a0
    - c-ares >=1.32.3,<2.0a0
    - libev >=4.33,<4.34.0a0
    - libev >=4.33,<5.0a0
    - libgcc >=13
    - libstdcxx >=13
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.3.2,<4.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
    - test -f ${PREFIX}/lib/libnghttp2.so
about:
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  dev_url: https://github.com/nghttp2/nghttp2
  doc_url: https://nghttp2.org/documentation/
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241022.1.1
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
  remote_url: https://github.com/conda-forge/nghttp2-feedstock
  sha: 970a96e770f3d092d485da395f750621d5c68510
