python:
  - 3.12
python_impl:
  - cpython
numpy:
  - 1.16
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
build_type:
  - release
  - debug                      # [not win]
channel_targets:
  - conda-forge main
  - conda-forge python_debug   # [not win]
zip_keys:
  - build_type
  - channel_targets
