# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jan  8 14:09:23 2025
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 2.4.0
source:
  sha256: a68d23d795704f1b687559b89c98e73d0dbebcab077592c60bffc1dc408b72e9
  url: https://github.com/conda/conda-package-handling/archive/2.4.0.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  noarch: python
  number: '2'
  script: /home/conda/feedstock_root/build_artifacts/conda-package-handling_1736345463896/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps -vv
  string: pyh7900ff3_2
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.2 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 h7b32b05_1
    - pip 24.3.1 pyh8b19718_2
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - conda-package-streaming >=0.9.0
    - python >=3.9
    - requests
    - zstandard >=0.15
test:
  commands:
    - pytest -v --cov=conda_package_handling --color=yes tests/
  imports:
    - conda_package_handling
    - conda_package_handling.api
  requires:
    - bottle
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
    - python 3.9.*
    - requests
  source_files:
    - tests
about:
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250108.3.1
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
    - msarahan
  remote_url: https://github.com/conda-forge/conda-package-handling-feedstock
  sha: 84708337f28f33545de59447205dd374b5a0cdb7
