# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Dec 10 07:08:21 2024
# ------------------------------------------------

package:
  name: jsonpatch
  version: '1.33'
source:
  sha256: 9fcd4009c41e6d12348b4a0ff2563ba56a2923a7dfee731d004e212e1ee5030c
  url: https://pypi.org/packages/source/j/jsonpatch/jsonpatch-1.33.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/jsonpatch_1733814567314/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.2 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - pandoc 3.5 ha770c72_0
    - pip 24.3.1 pyh8b19718_0
    - pypandoc 1.14 pyhd8ed1ab_1
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - jsonpointer >=1.9
    - python >=3.9
test:
  commands:
    - pip check
  imports:
    - jsonpatch
  requires:
    - pip
    - python 3.9.*
about:
  dev_url: https://github.com/stefankoegl/python-json-patch
  doc_url: https://python-json-patch.readthedocs.io/en/latest/
  home: https://github.com/stefankoegl/python-json-patch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Apply JSON-Patches (RFC 6902)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241210.1.1
  recipe-maintainers:
    - anguslees
    - pavelzw
    - pmlandwehr
  remote_url: https://github.com/conda-forge/jsonpatch-feedstock
  sha: 59e229dda493634b9870770f9bcc55be1c437ed1
