# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Dec  3 07:42:49 2024
# ------------------------------------------------

package:
  name: idna
  version: '3.10'
source:
  sha256: 12f65c9b470abda6dc35cf8e63cc574b1c52b11df2c86030af0ac09b01b13ea9
  url: https://pypi.org/packages/source/i/idna/idna-3.10.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/idna_1733211830134/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vvv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - flit-core 3.10.1 pyhd8ed1ab_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - pip 24.3.1 pyh8b19718_0
    - python 3.9.20 h13acc7a_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.9
test:
  imports:
    - idna
  requires:
    - python 3.9.*
about:
  description: 'A library to support the Internationalised Domain Names in Applications

    (IDNA) protocol as specified in RFC 5891. This version of the protocol

    is often referred to as "IDNA2008".

    '
  home: https://github.com/kjd/idna
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Internationalized Domain Names in Applications (IDNA).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241203.1.1
  recipe-maintainers:
    - goanpeca
    - jschueller
  remote_url: https://github.com/conda-forge/idna-feedstock
  sha: f3c2fed578e7a85f71b581a7cd55ee502708afe3
